field: 9ad7232b-940b-4762-85a7-0d9081a79992
fieldLayouts:
  c28f94c9-fd60-493d-a259-df240f357a38:
    tabs:
      -
        elements:
          -
            fieldUid: 8b2bae03-08dc-4c61-a255-dadc67cbc137
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70b753c2-54c0-47a5-8aa7-f394154eccf7
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  70b753c2-54c0-47a5-8aa7-f394154eccf7:
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8b2bae03-08dc-4c61-a255-dadc67cbc137:
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contactBlock
name: 'Contact Block'
sortOrder: 6
