field: 9ad7232b-940b-4762-85a7-0d9081a79992 # Content Matrix
fieldLayouts:
  89fa6d92-efc7-4e2b-b292-c5bcab9b38c4:
    tabs:
      -
        elements:
          -
            fieldUid: f9b7402d-9b4b-42fd-9961-429431a4b17a # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57123ace-d906-4162-b4e2-cd7d21a6a9f0 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 259116cd-e4bc-4d27-8ad6-0e6709d2022a # Photographer Instagram Handle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  259116cd-e4bc-4d27-8ad6-0e6709d2022a: # Photographer Instagram Handle
    contentColumnType: text
    fieldGroup: null
    handle: photographerInstagramHandle
    instructions: 'Anyone the photos should be attributed to'
    name: 'Photographer Instagram Handle'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  57123ace-d906-4162-b4e2-cd7d21a6a9f0: # Images
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f9b7402d-9b4b-42fd-9961-429431a4b17a: # Title
    contentColumnType: text
    fieldGroup: null
    handle: galleryTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: galleryBlock
name: 'Gallery Block'
sortOrder: 4
