field: 9ad7232b-940b-4762-85a7-0d9081a79992 # Content Matrix
fieldLayouts:
  7e0c7851-8a96-42f3-bf32-83578ce9e432:
    tabs:
      -
        elements:
          -
            fieldUid: 19176f80-a3fe-469e-b87d-9ca004aea297 # Gigs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  19176f80-a3fe-469e-b87d-9ca004aea297: # Gigs
    contentColumnType: string
    fieldGroup: null
    handle: gigs
    instructions: ''
    name: Gigs
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:8ed8686e-cb63-4d47-90d6-06750b461df7'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: gigsBlock
name: 'Gigs Block'
sortOrder: 3
