field: 9ad7232b-940b-4762-85a7-0d9081a79992
fieldLayouts:
  f25fa2dd-3347-47ed-aceb-28e9513e2cdd:
    tabs:
      -
        elements:
          -
            fieldUid: d99ba9e3-9ec5-48a3-ba77-850e280c069e
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 60bf46a8-2b75-44d5-98f3-c23a7122beed
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ebcee218-3931-484a-adbd-cfa3274dcfec
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2fe46c32-a515-49c3-8f9f-a79cbbeaa344
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0121b1dc-5593-429e-b6f7-d244d2ab07f0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c29b19f1-f5ee-47cc-a7e1-14b86ae8d930
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7edc1ff-7db0-4ec3-a768-8319cb732621
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a001db04-1e3e-4a40-92bd-b0b10ff2fa85
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1fe261a4-9f0c-41f3-b1af-b7c348f1610b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4e6e5d5c-d370-4a50-8d03-cc89ee8b47f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e076b39a-e660-4c2b-ab0a-07d908b8f7d9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7ef0c08c-6fb3-4120-bed8-0b4d110d2eae
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0121b1dc-5593-429e-b6f7-d244d2ab07f0:
    contentColumnType: string(255)
    fieldGroup: null
    handle: spotifyLink
    instructions: ''
    name: 'Spotify Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  1fe261a4-9f0c-41f3-b1af-b7c348f1610b:
    contentColumnType: string(255)
    fieldGroup: null
    handle: youTubeMusicLink
    instructions: ''
    name: 'YouTube Music Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  2fe46c32-a515-49c3-8f9f-a79cbbeaa344:
    contentColumnType: string(255)
    fieldGroup: null
    handle: imageLink
    instructions: ''
    name: 'Image Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  4e6e5d5c-d370-4a50-8d03-cc89ee8b47f6:
    contentColumnType: string(255)
    fieldGroup: null
    handle: amazonMusicLink
    instructions: ''
    name: 'Amazon Music Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  60bf46a8-2b75-44d5-98f3-c23a7122beed:
    contentColumnType: string
    fieldGroup: null
    handle: cover
    instructions: ''
    name: Cover
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:6b543568-4def-4735-bc26-59cf01f481c9'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7ef0c08c-6fb3-4120-bed8-0b4d110d2eae:
    contentColumnType: string(255)
    fieldGroup: null
    handle: dittoMusicLink
    instructions: ''
    name: 'Ditto Music Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a001db04-1e3e-4a40-92bd-b0b10ff2fa85:
    contentColumnType: string(255)
    fieldGroup: null
    handle: tidalLink
    instructions: ''
    name: 'Tidal Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  c29b19f1-f5ee-47cc-a7e1-14b86ae8d930:
    contentColumnType: string(255)
    fieldGroup: null
    handle: googlePlayMusicLink
    instructions: ''
    name: 'Google Play Music Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  c7edc1ff-7db0-4ec3-a768-8319cb732621:
    contentColumnType: string(255)
    fieldGroup: null
    handle: appleMusicLink
    instructions: ''
    name: 'Apple Music Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d99ba9e3-9ec5-48a3-ba77-850e280c069e:
    contentColumnType: text
    fieldGroup: null
    handle: releaseTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e076b39a-e660-4c2b-ab0a-07d908b8f7d9:
    contentColumnType: string(255)
    fieldGroup: null
    handle: deezerLink
    instructions: ''
    name: 'Deezer Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  ebcee218-3931-484a-adbd-cfa3274dcfec:
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: ''
    name: 'Image Position'
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: releaseBlock
name: 'Release Block'
sortOrder: 2
