field: 9ad7232b-940b-4762-85a7-0d9081a79992
fieldLayouts:
  42281693-ae51-4b97-8152-64d9f53d0588:
    tabs:
      -
        elements:
          -
            fieldUid: cdd449d3-8b4f-4b0a-8a60-6337a8aca928
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3dbf953b-dde2-4002-a387-86214d7f904a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88c46a63-e398-41c8-bb47-226756a3bfbc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3dbf953b-dde2-4002-a387-86214d7f904a:
    contentColumnType: string(255)
    fieldGroup: null
    handle: instagramLink
    instructions: ''
    name: 'Instagram Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  88c46a63-e398-41c8-bb47-226756a3bfbc:
    contentColumnType: string(255)
    fieldGroup: null
    handle: youtubeLink
    instructions: ''
    name: 'YouTube Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  cdd449d3-8b4f-4b0a-8a60-6337a8aca928:
    contentColumnType: string(255)
    fieldGroup: null
    handle: facebookLink
    instructions: ''
    name: 'Facebook Link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: socialLinksBlock
name: 'Social Links Block'
sortOrder: 5
